"""
Phase 2: Extract questions from page images via the configured vision provider.
- Groups pages by source file (one API call per paper)
- Caches results to avoid re-processing
- Returns structured JSON matching the schema
"""

import sys
import json
import re
from pathlib import Path
from collections import defaultdict
import base64

from src.config import (
    PAGES_DIR,
    EXTRACTED_DIR,
    EXTRACTION_PROVIDER,
    EXTRACTION_MODEL,
    api_key_for,
)
from src.llm import ImagePart, VisionRequest, ProviderError, get_provider


# Loaded so the model tags against the real syllabus vocabulary rather than
# inventing unit names. Generated by scripts/dump-syllabus-units.ts.
def load_unit_vocabulary(semester: int | None = None) -> str:
    """Every generated semester vocabulary, not just one.

    This was pinned to semester 6, which silently produced untaggable papers
    the moment a semester-2 or semester-4 scan went through: the model had no
    valid unit_id to choose and correctly left `units` empty. The semester is
    not known until the header is read, so all available vocabularies go in
    and the prompt's subject-code prefix rule does the selection.
    """
    schema_dir = Path(__file__).parent.parent / "schema"
    if semester is not None:
        paths = [schema_dir / f"units.sem{semester}.json"]
    else:
        paths = sorted(schema_dir.glob("units.sem*.json"))

    lines = []
    for path in paths:
        if not path.exists():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        lines.append(f'--- Semester {data["semester"]} ---')
        for subj in data["subjects"]:
            lines.append(f'{subj["subject_code"]} — {subj["subject_name"]}:')
            for u in subj["units"]:
                lines.append(f'  {u["unit_id"]}: {u["title"]}')
    return "\n".join(lines)


# One question, showing every field. Kept small on purpose — a full paper here
# would cost tokens on every call and invite copying rather than extracting.
EXTRACTION_SCHEMA = {
    "paper_id": "BIT351CO_2025_regular",
    "subject_code": "BIT351CO",
    "subject_name": "Artificial Intelligence",
    "semester": 6,
    "year": 2025,
    "exam_type": "regular",
    "curriculum": "new_course",
    "full_marks": 80,
    "pass_marks": 32,
    "duration_hours": 3,
    "extraction_notes": "anything the reviewer should know",
    "groups": [
        {
            "label": "A",
            "questions_printed": 3,
            "answer_count": 2,
            "marks_each": 12,
            "marks_total": 24,
            "instruction": "Answer TWO questions.",
        }
    ],
    "questions": [
        {
            "question_id": "BIT351CO_2025_regular_A1",
            "group": "A",
            "number": "1",
            "marks": 12,
            "text": "Define agent and show the architecture of an agent. Discuss the types of agent with suitable examples.",
            "question_type": "written",
            "units": [{"unit_id": "BIT351CO_U02", "confidence": "high"}],
            "has_diagram": True,
            "source_page": 1,
            "confidence": "high",
            "sub_parts": [
                {
                    "question_id": "BIT351CO_2025_regular_A1a",
                    "group": "A",
                    "number": "1a",
                    "marks": 4,
                    "text": "Define agent and show the architecture of an agent.",
                    "question_type": "written",
                    "units": [{"unit_id": "BIT351CO_U02", "confidence": "high"}],
                    "confidence": "high",
                }
            ],
        }
    ],
}


SYSTEM_PROMPT = """You are extracting exam questions from photographed Purbanchal University BIT
question papers from Nepal. Return ONLY valid JSON. No markdown fences, no
preamble, no explanation.

TRANSCRIPTION
- Transcribe question text EXACTLY as printed. Do not rephrase, correct
  grammar, or improve wording. Nepali-English textbook phrasing is preserved
  verbatim.
- If text is genuinely unreadable, set that field to null and set the
  question's confidence to "low". NEVER guess or invent a question.
- If a question refers to a figure, circuit, or table, set has_diagram true and
  describe it in one short phrase in square brackets inside the text.

HEADER
- The header gives subject_code (e.g. "BIT351CO"), subject name, year,
  full_marks, pass_marks and time. Read them; do not infer.
- Set curriculum from the SUBJECT CODE, not from the printed label: a code
  that appears in the VOCABULARY below is "new_course"; a code that does not
  appear there (BIT370CO, BIT371CO, BIT376CO, BIT415AI ...) is "old_course".
  Never leave curriculum null — the code is always printed.
  A printed "(New Course)" is NOT sufficient evidence: a 2022 BIT371CO paper
  also prints it, because that label was relative to a still earlier revision.
  Record the printed label verbatim in extraction_notes if it disagrees with
  the code.
- exam_type is "regular" unless the paper says back / make-up / model.

HANDWRITTEN CORRECTIONS — these papers are sometimes misprinted
- Invigilators correct errors on the printed paper by hand: striking out a
  word and writing the replacement above it, or writing a digit over another.
  A real example: "Answer SIX questions" with SIX struck out and "Seven"
  written above, and a printed "6x6=36" overwritten as "7x8=56".
- ALWAYS prefer the handwritten correction over the struck-out print, and say
  what you did in extraction_notes.
- Cross-check before you trust either: the groups' marks_total must sum to the
  header's full_marks. If they do not, you have mixed corrected and uncorrected
  values — re-read the page, and if it still does not reconcile, set the
  paper's extraction_notes to say so plainly rather than emitting numbers that
  do not add up.
- Ignore other handwriting: student names, roll numbers, and tick marks beside
  questions are not part of the paper.

GROUPS AND CHOICE — read this carefully, it is where papers differ
- Papers are divided into groups, each with an instruction and a mark formula,
  e.g. "Group A ... Answer TWO questions. 2x12=24".
- For each group record: label, questions_printed (how many questions are
  actually printed in that group), answer_count (how many the candidate must
  answer), marks_each, marks_total, and the instruction verbatim.
- questions_printed is usually LARGER than answer_count. Extract EVERY printed
  question, not just answer_count of them.
- full_marks equals the sum of the groups' marks_total, NOT the sum of every
  printed question's marks.

QUESTIONS AND SUB-PARTS
- A question with parts (a), (b), (c) is ONE question object whose `sub_parts`
  are FULL QUESTION OBJECTS — each with its own number, marks, text, and units.
  sub_parts must never be plain strings.
- Marks for sub-parts are often printed in the right margin as a split, e.g.
  "4+8" against a 12-mark question, or "3+6+3". Split the question at the
  natural sentence boundaries and assign those marks in order.
- If NO split is printed, set each sub-part's marks to null. Do not invent a
  division and never write 0 — the parent's total is the only figure the paper
  actually states, and a fabricated split would feed mark-weight analysis.
- If a split IS printed but you cannot match it confidently to the parts, set
  the question's confidence to "low" and leave sub_parts empty.
- If a question says "Write short notes on Any TWO:" over three options, set
  `choose` to 2 on that question and list all three options as sub_parts. Each
  option's marks are marks_total_of_question / choose.
- question_type is one of: "written" (prose answer), "numerical" (a worked
  calculation, proof, or puzzle whose specific numbers matter — cryptarithmetic,
  resolution proofs, simulations), "mcq", or "diagram".

SYLLABUS UNIT TAGGING
- Tag every question with at least one unit_id from the vocabulary below.
  If no unit is an obvious fit, choose the closest one and set that tag's
  confidence to "low". Leave `units` empty ONLY when the question is genuinely
  outside every listed unit — a question on neural networks in a subject whose
  units stop at clustering, for example. Say so in extraction_notes when you
  do; an empty list means "the syllabus vocabulary may be incomplete", not
  "I could not be bothered".
- Use ONLY unit_ids whose prefix matches the subject_code you read from the
  header. If the paper's subject is not in the vocabulary at all, leave units
  empty and say so in extraction_notes.
- More than one unit per question is normal and correct for cross-topic
  questions. Set each tag's confidence honestly: "high" only when the question
  clearly belongs to that unit.

VOCABULARY
{unit_vocabulary}
"""


def group_pages_by_paper():
    """Group page images by their source file. Return dict of paper_id -> list of page paths."""
    if not PAGES_DIR.exists():
        return {}

    pages = sorted(PAGES_DIR.glob("*.png"))
    papers = defaultdict(list)

    for page_path in pages:
        # Extract stem: "ai_2023_p1.png" -> "ai_2023"
        match = re.match(r"(.+)_p\d+\.png$", page_path.name)
        if match:
            stem = match.group(1)
            papers[stem].append(page_path)
        else:
            print(f"WARNING: Could not parse filename {page_path.name}, skipping")

    return papers


def encode_image(image_path):
    """Read image and encode as base64."""
    with open(image_path, "rb") as f:
        return base64.standard_b64encode(f.read()).decode("utf-8")


def extract_paper(paper_stem, page_paths):
    """Send all pages of one paper to API. Return extracted JSON dict or None on failure."""
    try:
        provider = get_provider(
            EXTRACTION_PROVIDER,
            api_key_for(EXTRACTION_PROVIDER),
            EXTRACTION_MODEL,
            need="vision",
        )
    except (ProviderError, ValueError) as e:
        print(f"ERROR: {e}")
        return None

    images = [
        ImagePart(data=path.read_bytes(), media_type="image/png")
        for path in sorted(page_paths)
    ]

    request = VisionRequest(
        system=SYSTEM_PROMPT.format(unit_vocabulary=load_unit_vocabulary()),
        text=(
            "Extract every question from this exam paper. Return only the JSON "
            "object.\n\nExpected schema:\n"
            f"{json.dumps(EXTRACTION_SCHEMA, indent=2)}\n"
        ),
        images=images,
        # Whole papers with sub-parts and marking detail overflow 4096; a
        # truncated response comes back as unparseable JSON, which reads like a
        # model failure rather than a limit.
        max_tokens=16000,
        json_only=True,
    )

    try:
        result = provider.complete_vision(request)
    except ProviderError as e:
        print(f"ERROR: {EXTRACTION_PROVIDER} extraction failed for {paper_stem}: {e}")
        return None

    print(
        f"       {result.provider}/{result.model} "
        f"in={result.usage.get('input_tokens')} out={result.usage.get('output_tokens')}"
    )

    text = result.text.strip()
    # Providers that cannot hard-constrain JSON may still wrap it in fences.
    text = re.sub(r"^```(?:json)?\n?", "", text)
    text = re.sub(r"\n?```$", "", text).strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError as e:
        print(f"ERROR: invalid JSON from {result.provider} for {paper_stem}: {e}")
        print(f"       first 200 chars: {text[:200]!r}")
        return None


def finalize(paper: dict, page_count: int) -> dict:
    """Compute the fields that must NOT come from the model.

    `coverage` and `needs_review` are the honesty mechanism — the whole point
    is that they cannot be quietly wrong. Asking the model to self-report its
    own completeness is exactly the failure this schema exists to prevent, so
    they are derived here from what was actually extracted.
    """
    questions = paper.get("questions") or []
    groups = paper.get("groups") or []

    counts: dict[str, int] = {}
    for q in questions:
        if isinstance(q, dict) and q.get("group") is not None:
            counts[q["group"]] = counts.get(q["group"], 0) + 1

    by_group = []
    status = "complete"
    for g in groups:
        if not isinstance(g, dict):
            continue
        label = g.get("label")
        got = counts.get(label, 0)
        printed = g.get("questions_printed") or 0
        by_group.append({
            "label": label,
            "questions_extracted": got,
            "questions_printed": printed,
        })
        if got < printed:
            status = "partial"
        elif got > printed and status != "partial":
            status = "over_extracted"

    if not groups:
        status = "partial"

    paper["coverage"] = {
        "by_group": by_group,
        "status": status,
        "notes": (
            "Derived from the extraction, not self-reported by the model."
            + ("" if status == "complete" else
               " Re-shoot or re-run before anything here is published.")
        ),
    }

    def roll_up_units(q: dict) -> list:
        """A parent's units are the union of its sub-parts'.

        The model reasonably tags the sub-parts of a split question and leaves
        the parent's list empty, but the schema requires every question to
        carry at least one unit — otherwise a question is untaggable and
        invisible to frequency counting. Deriving the parent from its children
        is exact, not a guess.
        """
        for sub in q.get("sub_parts") or []:
            if isinstance(sub, dict):
                roll_up_units(sub)
        if q.get("units"):
            return q["units"]
        merged: dict[str, dict] = {}
        for sub in q.get("sub_parts") or []:
            if not isinstance(sub, dict):
                continue
            for tag in sub.get("units") or []:
                uid = tag.get("unit_id")
                if uid and uid not in merged:
                    merged[uid] = dict(tag)
        if merged:
            q["units"] = list(merged.values())
        return q.get("units") or []

    def mark(q: dict) -> None:
        reasons = []
        if q.get("confidence") != "high":
            reasons.append(f"question confidence is {q.get('confidence')!r}")
        if not q.get("units"):
            reasons.append("no syllabus unit tagged")
        for tag in q.get("units") or []:
            if isinstance(tag, dict) and tag.get("confidence") == "low":
                reasons.append(f"low-confidence tag {tag.get('unit_id')}")
        if q.get("text") is None and not q.get("sub_parts"):
            reasons.append("text unreadable and no sub-parts captured")
        if status != "complete":
            reasons.append(f"paper coverage is {status}")

        q["needs_review"] = bool(reasons)
        if reasons:
            existing = q.get("notes")
            note = "; ".join(reasons)
            q["notes"] = f"{existing} | {note}" if existing else note
        for sub in q.get("sub_parts") or []:
            if isinstance(sub, dict):
                mark(sub)

    for q in questions:
        if isinstance(q, dict):
            roll_up_units(q)
            mark(q)

    paper.setdefault("source_files", [f"page {i + 1}" for i in range(page_count)])
    return paper


def infer_paper_id(paper_stem, extracted_data):
    """Infer paper_id from stem and extracted data. Format: {subject_code}_{year}_{exam_type}"""
    # Try to use paper_id from extracted data if present
    if extracted_data and "paper_id" in extracted_data and extracted_data["paper_id"]:
        return extracted_data["paper_id"]

    # Fallback: try to parse from stem
    # Format examples: "ai_2023", "software_eng_2021_back", "database_2024_regular"
    parts = paper_stem.split("_")

    year = None
    exam_type = "regular"

    for i, part in enumerate(parts):
        if part.isdigit() and len(part) == 4 and 2000 <= int(part) <= 2100:
            year = int(part)
            exam_type = "_".join(parts[i+1:]) if i + 1 < len(parts) else "regular"
            subject = "_".join(parts[:i])
            break

    if not year:
        return f"{paper_stem}_unknown"

    return f"{subject}_{year}_{exam_type}".upper()


def main():
    """Extract all papers."""
    papers = group_pages_by_paper()

    if not papers:
        print("No page images found in work/pages/")
        return

    print(f"Found {len(papers)} paper(s) to process\n")

    for paper_stem in sorted(papers.keys()):
        page_paths = papers[paper_stem]

        # Skip BEFORE spending an API call. This check used to run AFTER
        # extraction, so every re-run paid in full for papers already on disk
        # and then printed "SKIP" as though it had saved the work. Staged
        # filenames are the paper_id, so the prediction is exact; the
        # post-extraction check below still covers the case where the model
        # reads a different subject code off the header than the filename says.
        already = next(
            (
                EXTRACTED_DIR / f"{c}.json"
                for c in (paper_stem, infer_paper_id(paper_stem, None))
                if (EXTRACTED_DIR / f"{c}.json").exists()
            ),
            None,
        )
        if already is not None:
            print(f"SKIP: {already.stem} (already extracted, no API call)")
            continue

        temp_data = extract_paper(paper_stem, page_paths)
        if temp_data is None:
            paper_id = infer_paper_id(paper_stem, None)
            output_path = EXTRACTED_DIR / f"{paper_id}.FAILED.txt"
            output_path.write_text(f"API call failed for {paper_stem}\n")
            print(f"FAILED: {paper_id} — API extraction failed")
            continue

        paper_id = temp_data.get("paper_id") or infer_paper_id(paper_stem, temp_data)

        # Check if already extracted
        output_path = EXTRACTED_DIR / f"{paper_id}.json"
        if output_path.exists():
            print(f"SKIP: {paper_id}")
            continue

        # Ensure paper_id is set in output
        temp_data["paper_id"] = paper_id
        if "source_files" not in temp_data or not temp_data["source_files"]:
            temp_data["source_files"] = [str(p.relative_to(PAGES_DIR.parent.parent)) for p in page_paths]

        # Derive coverage and needs_review here, never from the model.
        temp_data = finalize(temp_data, page_count=len(page_paths))

        # Save JSON
        output_path.write_text(json.dumps(temp_data, indent=2, ensure_ascii=False), encoding="utf-8")

        # Count confidence levels
        questions = temp_data.get("questions", [])
        low_conf = sum(1 for q in questions if q.get("confidence") == "low")

        print(f"OK: {paper_id} — {len(questions)} questions ({low_conf} low confidence)")


if __name__ == "__main__":
    main()
